@echo off
echo Instalando dependencias do servidor...
cd Server && npm install

echo Instalando dependencias do cliente...
cd ../Client && npm install

echo Iniciando servidor em modo desenvolvimento...
cd ../Server && npm run dev
