[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd Server && npm install --production',
  'cd Client && npm install --production'
]

[phases.build]
cmds = ['cd Client && npm run build']

[start]
cmd = 'npm start'
