@echo off
echo Instalando dependencias do servidor...
cd Server && npm install

echo Instalando dependencias do cliente...
cd ../Client && npm install

echo Fazendo build do cliente...
npm run build

echo Iniciando servidor...
cd ../Server && npm start
